Import('*')

target = ['#output/analysis/top_gdp/top_gdp.txt']
source = ['#source/analysis/top_gdp/top_gdp_table.py',
          '#output/derived/wb_clean/gdp_education.csv']
env.Python(target, source) 

target = ['#output/analysis/top_gdp/top_gdp.tex']
source = ['#source/analysis/top_gdp/top_gdp_value.py',
          '#output/derived/wb_clean/gdp_education.csv']
env.Python(target, source) 

target = ['#output/analysis/plots/gdp_educ.eps',
          '#output/analysis/plots/gdp_educ.png']
source = ['#source/analysis/plots/plot_gdp_educ_exp.py',
              '#output/derived/wb_clean/gdp_education_logs.csv']
env.Python(target, source)


if mode == "full":
    target = ['#output/analysis/regressions/gdp_vs_educ_logs_2010.txt']
    source = ['#source/analysis/regressions/gdp_vs_educ_logs.m',
              '#output/derived/wb_clean/gdp_education_logs.csv']
    env.Matlab(target, source)

    target = ['#output/analysis/regressions/gdp_vs_educ_panel.txt']
    source = ['#source/analysis/regressions/gdp_vs_educ_panel.R',
              '#output/derived/wb_clean/gdp_education_panel.csv']
    env.R(target, source)
