Import('*')

target = ['#source/figures/gdp_educ.lyx']
source = ['#output/analysis/plots/gdp_educ.eps']

env.Dependency(target, source)

target = ['#source/figures/gdp_educ.tex']
source = ['#output/analysis/plots/gdp_educ.eps']

env.Dependency(target, source)
